In [1]:
import numpy as np
import pandas as pd

In [2]:
#加载数据
data = pd.read_csv('./保健品问卷数据/保健品.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   q5_01   625 non-null    int64
 1   q5_02   625 non-null    int64
 2   q5_03   625 non-null    int64
 3   q5_04   625 non-null    int64
 4   q5_05   625 non-null    int64
 5   q5_06   625 non-null    int64
 6   q5_07   625 non-null    int64
 7   q5_08   625 non-null    int64
 8   q5_09   625 non-null    int64
 9   q5_10   625 non-null    int64
 10  q5_11   625 non-null    int64
 11  q5_12   625 non-null    int64
 12  q5_13   625 non-null    int64
 13  q5_14   625 non-null    int64
 14  q5_15   625 non-null    int64
 15  q5_16   625 non-null    int64
 16  q5_17   625 non-null    int64
 17  q5_18   625 non-null    int64
 18  q5_19   625 non-null    int64
 19  q5_20   625 non-null    int64
 20  q8      625 non-null    int64
 21  w1      625 non-null    int64
 22  w2      625 non-null    int64
 23  w6      625 non-null    int64
dtypes: int64(24)
memory usage: 117.3 KB

In [4]:
data.describe()

,q5_01,q5_02,q5_03,q5_04,q5_05,q5_06,q5_07,q5_08,q5_09,q5_10,...,q5_15,q5_16,q5_17,q5_18,q5_19,q5_20,q8,w1,w2,w6
count,625.000000,625.000000,625.0000,625.000000,625.000000,625.000000,625.000000,625.000000,625.000000,625.000000,...,625.00000,625.000000,625.000000,625.000000,625.000000,625.000000,625.000000,625.000000,625.000000,625.000000
mean,3.804800,3.932800,4.1552,3.305600,2.760000,3.276800,3.683200,3.643200,3.750400,3.900800,...,4.03200,3.868800,2.694400,3.036800,3.032000,3.275200,6.182400,1.724800,3.235200,8.481600
std,1.288625,1.173408,1.0454,1.485308,1.561763,1.545835,1.353576,1.382951,1.371097,1.149031,...,1.18711,1.261639,1.559005,1.386839,1.358355,1.417985,2.947513,0.446973,1.219779,10.334939
min,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3.000000,3.000000,4.0000,2.000000,1.000000,2.000000,3.000000,3.000000,3.000000,3.000000,...,3.00000,3.000000,1.000000,2.000000,2.000000,2.000000,3.000000,1.000000,2.000000,6.000000
50%,4.000000,4.000000,4.0000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,4.00000,4.000000,2.000000,3.000000,3.000000,3.000000,7.000000,2.000000,3.000000,8.000000
75%,5.000000,5.000000,5.0000,5.000000,4.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.00000,5.000000,4.000000,4.000000,4.000000,5.000000,9.000000,2.000000,4.000000,10.000000
max,5.000000,5.000000,5.0000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,9.000000,2.000000,7.000000,99.000000

In [5]:
data['q8'].value_counts()

9    282
3     83
7     55
5     55
1     55
4     40
2     32
6     23
Name: q8, dtype: int64

In [6]:
data['w1'].value_counts()

2    453
1    172
Name: w1, dtype: int64

In [10]:
#切出前20列 做子集，然后进行题目相关分析
sub_data=data.loc[:,:'q5_20']
sub_data

,q5_01,q5_02,q5_03,q5_04,q5_05,q5_06,q5_07,q5_08,q5_09,q5_10,q5_11,q5_12,q5_13,q5_14,q5_15,q5_16,q5_17,q5_18,q5_19,q5_20
0,3,3,4,5,5,5,4,5,3,4,4,4,3,4,5,5,2,3,4,4
1,5,4,5,5,5,5,5,4,4,4,4,3,4,4,5,5,5,4,4,5
2,5,5,5,5,1,1,4,1,1,1,5,1,1,5,5,1,1,5,1,1
3,3,5,5,1,1,1,4,5,4,4,4,2,3,4,3,4,4,1,1,5
4,5,4,2,2,3,4,4,3,4,3,2,5,3,2,3,4,3,4,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,3,4,4,1,1,5,4,4,5,4,5,1,4,5,5,5,5,5,1,1
621,4,3,5,4,3,4,5,4,4,4,5,3,4,3,5,4,3,4,5,3
622,3,4,5,4,4,1,4,5,5,4,5,1,4,5,5,4,1,1,1,1
623,4,4,3,5,1,5,4,4,4,5,5,4,3,5,5,1,4,4,2,5
624,5,5,5,3,1,2,4,2,2,4,4,4,1,4,5,5,1,1,1,4

In [11]:
sub_data.mean()

q5_01    3.8048
q5_02    3.9328
q5_03    4.1552
q5_04    3.3056
q5_05    2.7600
q5_06    3.2768
q5_07    3.6832
q5_08    3.6432
q5_09    3.7504
q5_10    3.9008
q5_11    3.8448
q5_12    3.1392
q5_13    3.4384
q5_14    3.6656
q5_15    4.0320
q5_16    3.8688
q5_17    2.6944
q5_18    3.0368
q5_19    3.0320
q5_20    3.2752
dtype: float64

In [12]:
sub_data.corr()

,q5_01,q5_02,q5_03,q5_04,q5_05,q5_06,q5_07,q5_08,q5_09,q5_10,q5_11,q5_12,q5_13,q5_14,q5_15,q5_16,q5_17,q5_18,q5_19,q5_20
q5_01,1.000000,0.598599,0.271154,0.284914,0.156647,0.270931,0.303516,0.176677,0.269885,0.105957,0.195620,0.294367,0.137726,0.227503,0.183230,0.137009,0.203986,0.169025,0.130834,0.209238
q5_02,0.598599,1.000000,0.354718,0.263744,0.149467,0.296523,0.324584,0.189624,0.300337,0.226824,0.231136,0.308576,0.095120,0.259278,0.200577,0.131513,0.172722,0.157118,0.116976,0.176795
q5_03,0.271154,0.354718,1.000000,0.198529,0.070947,0.186584,0.226200,0.171381,0.220494,0.283668,0.274368,0.275149,0.114429,0.229642,0.318828,0.196507,0.102895,0.063482,0.039382,0.113845
q5_04,0.284914,0.263744,0.198529,1.000000,0.347387,0.463543,0.265842,0.175656,0.244475,0.116387,0.083279,0.268755,0.191097,0.200181,0.121689,0.029127,0.110295,0.118232,0.145268,0.139577
q5_05,0.156647,0.149467,0.070947,0.347387,1.000000,0.232011,0.153497,0.162850,0.086485,0.047438,0.010905,0.213633,0.119648,0.055136,0.091452,0.069393,0.194272,0.126908,0.147155,0.184010
q5_06,0.270931,0.296523,0.186584,0.463543,0.232011,1.000000,0.413435,0.289901,0.419777,0.191420,0.144427,0.285872,0.164459,0.356856,0.147119,0.095070,0.125593,0.115593,0.175890,0.085825
q5_07,0.303516,0.324584,0.226200,0.265842,0.153497,0.413435,1.000000,0.216041,0.289774,0.170383,0.177249,0.292511,0.095355,0.208690,0.197808,0.155799,0.194786,0.193181,0.220809,0.159049
q5_08,0.176677,0.189624,0.171381,0.175656,0.162850,0.289901,0.216041,1.000000,0.396668,0.217714,0.166411,0.240564,0.321282,0.293451,0.201220,0.079672,0.057866,0.063676,0.092250,0.132691
q5_09,0.269885,0.300337,0.220494,0.244475,0.086485,0.419777,0.289774,0.396668,1.000000,0.315872,0.182697,0.275607,0.229453,0.509146,0.240232,0.090357,0.120200,0.057091,0.138528,0.159854
q5_10,0.105957,0.226824,0.283668,0.116387,0.047438,0.191420,0.170383,0.217714,0.315872,1.000000,0.381777,0.266328,0.166990,0.272992,0.290176,0.071707,0.049251,0.071686,0.071857,0.048257
q5_11,0.195620,0.231136,0.274368,0.083279,0.010905,0.144427,0.177249,0.166411,0.182697,0.381777,1.000000,0.362240,0.200766,0.210698,0.291862,0.080952,0.051245,0.097182,0.038478,0.053135
q5_12,0.294367,0.308576,0.275149,0.268755,0.213633,0.285872,0.292511,0.240564,0.275607,0.266328,0.362240,1.000000,0.284479,0.284984,0.192133,0.135815,0.177992,0.275833,0.224939,0.210532
q5_13,0.137726,0.095120,0.114429,0.191097,0.119648,0.164459,0.095355,0.321282,0.229453,0.166990,0.200766,0.284479,1.000000,0.275313,0.154039,0.099737,0.095834,0.095614,0.091202,0.154044
q5_14,0.227503,0.259278,0.229642,0.200181,0.055136,0.356856,0.208690,0.293451,0.509146,0.272992,0.210698,0.284984,0.275313,1.000000,0.379412,0.085116,0.123176,0.109453,0.155211,0.119721
q5_15,0.183230,0.200577,0.318828,0.121689,0.091452,0.147119,0.197808,0.201220,0.240232,0.290176,0.291862,0.192133,0.154039,0.379412,1.000000,0.197550,0.037331,0.166711,0.091790,0.148038
q5_16,0.137009,0.131513,0.196507,0.029127,0.069393,0.095070,0.155799,0.079672,0.090357,0.071707,0.080952,0.135815,0.099737,0.085116,0.197550,1.000000,0.285934,0.192358,0.158619,0.254913
q5_17,0.203986,0.172722,0.102895,0.110295,0.194272,0.125593,0.194786,0.057866,0.120200,0.049251,0.051245,0.177992,0.095834,0.123176,0.037331,0.285934,1.000000,0.385451,0.320192,0.326627
q5_18,0.169025,0.157118,0.063482,0.118232,0.126908,0.115593,0.193181,0.063676,0.057091,0.071686,0.097182,0.275833,0.095614,0.109453,0.166711,0.192358,0.385451,1.000000,0.568492,0.387636
q5_19,0.130834,0.116976,0.039382,0.145268,0.147155,0.175890,0.220809,0.092250,0.138528,0.071857,0.038478,0.224939,0.091202,0.155211,0.091790,0.158619,0.320192,0.568492,1.000000,0.370659
q5_20,0.209238,0.176795,0.113845,0.139577,0.184010,0.085825,0.159049,0.132691,0.159854,0.048257,0.053135,0.210532,0.154044,0.119721,0.148038,0.254913,0.326627,0.387636,0.370659,1.000000

In [13]:
corr=sub_data.corr()
corr[corr<0.3] = 0
corr[corr>0.3] = 999
corr

,q5_01,q5_02,q5_03,q5_04,q5_05,q5_06,q5_07,q5_08,q5_09,q5_10,q5_11,q5_12,q5_13,q5_14,q5_15,q5_16,q5_17,q5_18,q5_19,q5_20
q5_01,999.0,999.0,0.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_02,999.0,999.0,999.0,0.0,0.0,0.0,999.0,0.0,999.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_03,0.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0
q5_04,0.0,0.0,0.0,999.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_05,0.0,0.0,0.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_06,0.0,0.0,0.0,999.0,0.0,999.0,999.0,0.0,999.0,0.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_07,999.0,999.0,0.0,0.0,0.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_09,0.0,999.0,0.0,0.0,0.0,999.0,0.0,999.0,999.0,999.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_12,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
q5_14,0.0,0.0,0.0,0.0,0.0,999.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0
q5_15,0.0,0.0,999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,0.0,0.0,0.0,0.0,0.0
q5_16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,0.0,0.0,0.0,0.0
q5_17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,999.0,999.0
q5_18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,999.0,999.0
q5_19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,999.0,999.0
q5_20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999.0,999.0,999.0,999.0